### ISSUE TITLE
identify_key

### ISSUE THREAD

**Issue by zarc70** [holy-tanuki/wombopy#1]
Hi,

Can you please explain identify_key? Is the a requirement to have access to the Wombo API or something else?

**Comment by holy-tanuki** [comment]
### To get an identify_key:
 - Go to https://app.wombo.art/
 - Open the devtools and go to the `network` tab
 - Find a request from "https://identitytoolkit.googleapis.com/v1/accounts" and get the `key` parameter in the url.

### Exemple:
url: "https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=BIMaSyDCvp5MkJLUdtBYEKYXXiolLzu1zuKM5cV"
key: `BIMaSyDCvp5MkJLUdtBYEKYXXiolLzu1zuKM5cV`
