### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by tea513** [holy-tanuki/wombopy#2]
Excuse me, how to use it.... I only know that it is cli, and I need steps from beginning to end. I am new to py

**Comment by holy-tanuki** [comment]
No worries, to use wombopy follow this steps:
- **Dowload it** (obviously) but make sure it's the **version 0.1.3**
- After that type `python -m wombopy --version` if you're using windows and `python3 -m wombopy --version` else
- If all works, go check the issue #1 to get an identify_key
- And finally type `python -m wombopy {your identify_key} "a random prompt" 3 --show` (3 is the style)

Your command would be look like this: `python -m wombopy run AbzaSyDCvp5MTJLUdtBYEYJWXJrlLzu2zbKM6xW "death" 3 --show`
